config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'transactions#index'

  resources :users
  resources :transactions

  get '/account', to: 'users#account'
  get '/cashin', to: 'transactions#cashin'
  post '/cashin', to: 'transactions#cashin_post'
  get '/buy', to: 'transactions#buy'
  get '/purchase/:company/:price', to: 'transactions#purchase'
  post '/purchase/:company/:price', to: 'transactions#purchase_post'
  get '/portfolio', to: 'users#portfolio'
  get '/sell', to: 'transactions#sell'
  get '/sale/:company/:price', to: 'transactions#sale'
  post '/sale/:company/:price', to: 'transactions#sale_post'
  get '/user/new', to: 'users#new'
  post '/user/new', to: 'users#create'
  get '/user/:id/edit', to: 'users#edit'
  patch '/user/:id/edit', to: 'users#update'
  get '/restricted', to: 'users#restricted'
  patch '/approve/:id', to: 'users#approve'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :transactions

  validates :name, presence: true, uniqueness: true, allow_nil: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_id
  before_action :check_admin,
                only: %i[index show new create edit update approve]
  before_action :check_non_admin, only: %i[account]
  before_action :set_user, only: %i[show edit update]
  before_action :set_client, only: %i[portfolio]
  before_action :set_portfolio, only: %i[portfolio]
  before_action :check_approved,
                only: %i[index show new create edit update account portfolio]

  def index
    @users = User.where(admin: false).order('created_at DESC')
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'Successfully created new account.'
    else
      redirect_to '/user/new', alert: 'Invalid input.'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'User was successfully updated.'
    else
      redirect_to '/user/' + @user.id.to_s + '/edit', alert: 'Invalid input.'
    end
  end

  def account
    @balance = Transaction.where(user_id: @user_id).pluck(:amount).sum
    @user = current_user
  end

  def approve
    @user = User.find(params[:id])
    @user.update(approved: true)
    redirect_to users_path, notice: @user.name + ' has been approved'
  end

  def portfolio; end

  private

  def set_user_id
    @user_id = current_user.id
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_admin
    redirect_to root_path if !current_user.admin
  end

  def check_non_admin
    redirect_to root_path if current_user.admin
  end

  def check_approved
    redirect_to restricted_path if !current_user.approved
  end

  def user_params
    params.require(:user).permit(:email, :password, :name)
  end

  def set_portfolio
    transactions =
      Transaction.where(user_id: @user_id).where.not(action: 'cash in')

    portfolio = {}

    transactions.each do |transaction|
      if portfolio[transaction.stock]
        if transaction.action == 'purchase'
          portfolio[transaction.stock] += transaction.quantity
        elsif transaction.action == 'sale'
          portfolio[transaction.stock] -= transaction.quantity
        end
      else
        if transaction.action == 'purchase'
          portfolio[transaction.stock] = transaction.quantity
        elsif transaction.action == 'sale'
          portfolio[transaction.stock] = -transaction.quantity
        end
      end
    end

    @portfolio = portfolio.select { |k, v| v > 0 }
  end

  def set_client
    @client =
      IEX::Api::Client.new(
        publishable_token: 'Tsk_006d6aef7d2c42b389a9e6aa87636847',
        secret_token: 'Tpk_d2717c1f6e6e4837a40e8753fd3836be',
        endpoint: 'https://sandbox.iexapis.com/v1',
      )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show.html.erb
<div class="box">
  <h2><%= user.name %></h2>
  <br>
  <table>
    <tr>
      <td>Approved:</td>
      <td>
        <% if  user.approved %>
          <span>Yes</span>
        <% else %>
          <span>No</span>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Email:</td>
      <td><%= user.email %></td>
    </tr>
    <tr>
      <td>Date Created:</td>
      <td><%= user.created_at.localtime.to_s.split(" ")[0] %></td>
    </tr>
    <tr>
      <td>Time Created:</td>
      <td><%= user.created_at.localtime.to_s.split(" ")[1] %></td>
    </tr>
  </table>
</div>

app/views/users/_user.html.erb
<% if user.approved %>
  <div class="box">
    <table>
      <tr>
        <td>
          <img src='/images/thumb-up.svg'/>
        </td>
        <td class="width200px">
          <span class="enlarge">
            <%= user.name %>
          </span>
        </td>
        <td><%= link_to 'Details', user_path(user) %></td>
        <td><%= link_to 'Edit', '/user/' + user.id.to_s + '/edit' %></td>
      </tr>
    </table>
  </div>
<% else %>
  <div class="box">
    <table>
      <tr>
        <td>
          <img src='/images/thumb-down.svg'/>
        </td>
        <td class="width200px">
          <span class="enlarge">
            <%= user.name %>
          </span>
        </td>
        <td><%= link_to 'Details', user_path(user) %></td>
        <td><%= link_to 'Edit', '/user/' + user.id.to_s + '/edit' %></td>
        <td><%= link_to 'Approve', '/approve/' + user.id.to_s, :class => 'button', method: :patch %></td>
      </tr>
    </table>
  </div>
<% end %>

app/views/users/account.html.erb
<div class="box">
  <h2>Balance</h2>
  <br>
  <h1 class="purple">
    <%= number_to_currency(@balance) %>
  </h1>
  <br>
  <%= link_to 'Cash In', cashin_path, :class => 'button' %>
</div>
<%= render 'users/show', user: @user %>

app/views/users/edit.html.erb
<div class="box">
  <h2>Edit User</h2>
  <%= form_with(model: @user, url: "/user/" + @user.id.to_s + "/edit") do |f| %>
    <div>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email, "Email" %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.submit "Update User" %>
    </div>
  <% end %>
</div>
<%= link_to 'Back', users_path, :class => 'button' %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= render @users %>
<% if @users.length < 1 %>
  <div class="box">
    <h2>No users have been created yet.</h2>
  </div>
<% end %>
<%= link_to 'Create User', '/user/new', :class => 'button' %>

app/views/users/new.html.erb
<div class="box">
  <h2>New User</h2>
  <%= form_with(model: @user, url: "/user/new") do |f| %>
    <div>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email, "Email" %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :password, "Password" %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.submit "Create User" %>
    </div>
  <% end %>
</div>
<%= link_to 'Back', users_path, :class => 'button' %>

app/views/users/portfolio.html.erb
<h1>Portfolio</h1>
<% sum = 0 %>
<div class="grid">
  <% @portfolio.each do |stock, quantity| %>
    <div class="box">
      <h2><%= stock %></h2>
      <br>
      <% details = @client.quote(stock) %>
      <% if details.change_percent > 0 %>
        <h1 class='green'><%= number_to_currency(details.latest_price * quantity) %></h1>
      <% elsif details.change_percent < 0 %>
        <h1 class='red'><%= number_to_currency(details.latest_price * quantity) %></h1>
      <% else %>
        <h1 class='purple'><%= number_to_currency(details.latest_price * quantity) %></h1>
      <% end %>
      <% sum += details.latest_price * quantity %>
      <br>
      <table>
        <tr>
          <td>
            Quantity: 
          </td>
          <td>
            <%= quantity %>
          </td>
        </tr>
        <tr>
          <td>
            Latest Price: 
          </td>
          <td>
            <%= number_to_currency(details.latest_price) %>
          </td>
        </tr>
      </table>
    </div>
  <% end %>
</div>
<% if @portfolio.length < 1 %>
  <div class="box">
    <h2>No stocks in portfolio yet.</h2>
    <br>
    <%= link_to 'Buy some here!', buy_path, :class => 'button' %>
  </div>
<% end %>
<div class="box">
  <h1 class='purple'>Total Value: <%= number_to_currency(sum) %></h1>
</div>

app/views/users/restricted.html.erb
<div class="box">
  <h2>
    This content is restricted because your account has not yet been approved.
  </h2>
</div>

app/views/users/show.html.erb
<%= render 'users/show', user: @user %>
<%= link_to 'Back', users_path, :class => 'button' %>