config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'transactions#index'

  resources :users
  resources :transactions

  get '/account', to: 'users#account'
  get '/cashin', to: 'transactions#cashin'
  post '/cashin', to: 'transactions#cashin_post'
  get '/buy', to: 'transactions#buy'
  get '/purchase/:company/:price', to: 'transactions#purchase'
  post '/purchase/:company/:price', to: 'transactions#purchase_post'
  get '/portfolio', to: 'users#portfolio'
  get '/sell', to: 'transactions#sell'
  get '/sale/:company/:price', to: 'transactions#sale'
  post '/sale/:company/:price', to: 'transactions#sale_post'
  get '/user/new', to: 'users#new'
  post '/user/new', to: 'users#create'
  get '/user/:id/edit', to: 'users#edit'
  patch '/user/:id/edit', to: 'users#update'
  get '/restricted', to: 'users#restricted'
  patch '/approve/:id', to: 'users#approve'
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<div class='navbar'>
  <div class="navleft">
    <img src='/images/dollar.svg'/>
    <span>stocks.</span>
  </div>
  <div class="navright">
    <% if user_signed_in? %>
      <%= link_to 'Transactions', transactions_path %>
      <% if current_user.admin %>
        <%= link_to 'Users', users_path %>
      <% else %>
        <%= link_to 'Portfolio', portfolio_path %>
        <%= link_to 'Buy', buy_path %>
        <%= link_to 'Sell', sell_path %>
        <%= link_to 'Account', account_path %>
      <% end %>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete, :class => 'signout' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>stocks.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/x-icon" href="/images/dollar.svg">
  </head>
  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/navbar' %>
    <div class='main'>
      <%= yield %>
    </div>
  </body>
</html>